version: "3.8"

services:
  goaccess:
    container_name: goaccess
    image: memphisx/rpi-goaccess
    command: --config-file=/goaccess/goaccess.conf --ignore-panel=REQUESTS_STATIC --ignore-panel=REFERRERS --ignore-panel=REFERRING_SITES --ignore-panel=KEYPHRASES --ignore-panel=STATUS_CODES --ignore-panel=NOT_FOUND
    environment:
      - TZ=Europe/Prague
    volumes:
      - ${PWD}/goaccess:/goaccess
      - ${PWD}/log:/log
    ports:
      - 7890:7890 # goaccess websocket

  goaccess-nginx:
    container_name: goaccess-nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/log:/var/log/nginx
      - ${PWD}/goaccess/html:/var/www
      - ${PWD}/certbot/conf:/etc/letsencrypt
      - ${PWD}/certbot/www:/var/www/certbot
    image: tobi312/rpi-nginx:alpine
    ports:
      - 80:80 # certbot
      - 443:443 # tracking pixel
      - 7891:8081 # goaccess report

  goaccess-certbot:
    container_name: goaccess-certbot
    image: certbot/certbot:arm32v6-latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
